### ISSUE TITLE
Update the tagging to be a centralized source

### ISSUE THREAD

**Issue by jimmyrocks** [nationalparkservice/places-data#106]
Outstanding tasks:
## Tagging:
- [x] Create new tags for POI versions of things that are both points and lines
- [x] Create new tags for POI versions of things that are both points and polygons
- [x] Go through the HFC list and update/verify each and every POI with a Category from the HFC list
- [ ] Go through each and every POI and assign the subcategory level to an icon, or leave blank for unknown (Jake and @mtaylorlong)
- [ ] Go through the trails and make sure they haven't gotten changed too far from the original plan
  do the same thing for roads, barrier, buildings, and parking lots (Chad and Nate)
- [ ] Add a description for each tag (Chad) (now here https://github.com/nationalparkservice/places-tracing-guide/issues/27)
- [ ] add a howToMap for each tag (Chad) (now here https://github.com/nationalparkservice/places-tracing-guide/issues/27)
- [x] Determine a way to describe each category for the tracing guide (Jim and @mtaylorlong)
- [ ] Figure out a way to get the information from the "fields" into the tracing guide (Chad, Jim, and Nate) (now here https://github.com/nationalparkservice/places-tracing-guide/issues/27)
- [x] Follow up with Alaska to see if we're removing any tags that they need (Chad)
## iD
- [x] Clean up how the list is made from the tags (this includes a schema verification, like iD currently does)
- [x] Change the path to point to the new file (Jim)
- [ ] Change the information links to point to the tracing guide (Chad and Nate) (now here https://github.com/nationalparkservice/places-editor/issues/59)
- [x] Figure out if we need to have tags specifically for categories, how to add those in our schema
  since the fields are still in iD and the import script is not, we need to figure out a way to verify that a field exists before adding it to the preset, otherwise iD will crash (Jim) (Sounds like we should include places-editor as a submodule in this repository, and they will stay in sync.)
## Rendering
- [x] There is currently a script called o2p_get_name: https://github.com/nationalparkservice/places-api/blob/3654cb0fbb34c48aabce914249048109ecaa6516/scripts/sql_scripts/pgs/nps_tools.sql#L282-L401
- [x] This needs to be updated to return a set of results (cat, subcat, name, zorder) as opposed to a string, which it is currently returning
- [x] There is a currently a function called:  nps_node_o2p_calculate_zorder  This will need to be removed and replaced by the updated o2p_get_name function
- [x] This will require the following tables in the API to be updated:
- [x] nps_render_point
- [x] nps_render_polygon
- [x] nps_render_line

And the following views:
- [x] nps_planet_osm_point_view
- [x] nps_planet_osm_polygon_view
- [x] nps_planet_osm_line_view

And the following functions:
- [x] o2p_render_element
## Display

There are other tasks that involve the rewriting of CartoCSS that are not listed here

**Comment by nateirwin** [comment]
Closing this for now. The outstanding items have been moved into individual issues.
