### ISSUE TITLE
Clean up CartoDB parks table

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-data#245]
Not sure how we want to deal with these, but I think it's time to clean them up:
- [x] We have both "Fredricksburg" and "Fredricksburg & Spotsylvania National Military Park". I think we should get rid of "Fredricksburg" (https://github.com/nationalparkservice/places-data/issues/318).
- [x]  We have two records for "Thomas Jefferson Memorial" (https://github.com/nationalparkservice/places-data/issues/319).
- [x]  We have both "National Mall" and "National Mall & Memorial Parks" (https://github.com/nationalparkservice/places-data/issues/320).
- [x]  We have two administrative units I'm not sure we need: "National Capital Parks" and "National Capital Parks - East". This is an interesting case. I don't know if we need these two units at all, as they are really just administrative units. The parks (and labels) we're interested in are all subunits of these two. This is related to what @mtaylorlong has been thinking about. (https://github.com/nationalparkservice/places-data/issues/322)
- [x]  "Obed Wild & Scenic River" is in the table twice (https://github.com/nationalparkservice/places-data/issues/68).

I believe the encoding of the name in the screenshot below may be incorrect.

![editor___places___insidemaps](https://cloud.githubusercontent.com/assets/10443/10999557/fd29e830-8459-11e5-85e0-6ee7561a29d7.jpg)

**Comment by mtaylorlong** [comment]
Glad you brought this up @nateirwin – I've been thinking about these tables a lot as well. I think the sooner we switch over to our new boundaries table, the better.

I think our new boundaries table (which we've actually renamed to "parks") is in good enough shape to be our new source for rendering out to cartodb, but @jimmyrocks should chime in on this as well. Our parks table certainly has more fields than we need in the cartodb table, so perhaps we could generate a materialized view specifically for pushing to cartodb. We could also take this moment to figure out what we're missing – our table only has 404 records, and I know there are more parks than that, so we should get that sorted out.

I'd love to put together a little outline of what we need in the cartodb tables to power our other apps. I also have some thoughts on the issue of how we can accommodate subunits.

**Comment by mtaylorlong** [comment]
I've outlined my thoughts on how our parks db should be set up in this document: https://github.com/nationalparkservice/places-data/blob/gh-pages/boundaries/database_structure.md

**Comment by jimmyrocks** [comment]
This is great! thanks!

**Comment by chadlawlis** [comment]
See also: https://github.com/nationalparkservice/places-data/issues/315.

We can clean any remaining issues up as we create the new CartoDB table, which will pull from the PostGIS Parks table (`parks` in `places_boundaries`).

**Comment by cwlawlis802** [comment]
- [ ] Resolve `designation` != `full_designation` and remove `full_designation`

**Comment by chadlawlis** [comment]
See here https://github.com/nationalparkservice/places-data/issues/68 for OBRI. This issue has been resolved in CartoDB, but PT3 labeling and boundary rendering (https://github.com/nationalparkservice/places-data/issues/321) issues remain.

**Comment by chadlawlis** [comment]
Closing this out - all outstanding issues are being tracked separately (all DC issues via https://github.com/nationalparkservice/places-data/labels/ncr-cleanup and FRED vs. FRSP is still being figured out https://github.com/nationalparkservice/places-data/issues/318). Otherwise, a new `parks` CartoDB table is on its way so no need to track places_boundaries server vs. CartoDB parks tables issues separately.
