### ISSUE TITLE
Lands feedback on PT3 boundaries

### ISSUE THREAD

**Issue by chadlawlis** [nationalparkservice/places-data#515]
From Roger @ Lands, 1/25/16:

> I've been consolidating comments from the National and Regional Lands offices on the Park Tiles 3 Beta prior to it going public in February.  This list doesn't cover all NPS units.  It's just the comments I have received to date.
- [ ] Lands 4/22/15 IRMA update is not reflected in the NPMap or Park Tiles. #538
- [ ] Lands 7/23/15 IRMA update is not reflected in the NPMap or Park Tiles. #537
- [x] Lands 9/30/15 IRMA update is not reflected in the NPMap or Park Tiles. #445 
- [x] Lands 12/31/15 IRMA update is not reflected in the NPMap or Park Tiles. #362 
- [x] The ORCA boundary still does not reflect the addition of the Preserve.  This was updated in Lands data 9 months ago. #536
- [x] It appears all park boundaries for Alaska are old. We have revised the coastlines, etc. in many places and it looks like they are using linework from 2+ years ago.
  - all AKR boundaries now pulling from latest Lands release 20160107
- [ ] The Alaska shoreline appears to be overly generalized.  What is the generalization process?
- [x] PIPE is named twice when zoomed part way in. #516
- [x] VOYA is named twice when zoomed out but only once when zoomed in. #517
- [x] GRPO is named twice when zoomed out but only once when zoomed in. #518
- [x] PULL marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z8, will not render before then
  - change under consideration via #519
- [x] IATR is missing.
  - we do not currently render/support National Trails
- [x] INDU marked doesn't show when zoomed out.  The name only shows when zoomed way in.
  - `min_zoom_label` intentionally set to Z8, will not render before then
  - change under consideration via #519
- [x] GERO is named twice when zoomed part way in. #520
- [x] WIHO is missing.
  - it's here: http://insidemaps.nps.gov/park-tiles-3/#19/39.11973/-84.50733
- [x] HOCU marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z7, will not render before then
- [x] CHYO  marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z9, will not render before then
- [x] FILA  marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z8, will not render before then
- [x] CUVA is named twice when zoomed part way in. #521
- [x] PEVI  marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z8, will not render before then
- [x] JAGA  marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z8, will not render before then
- [x] RIRA  marker is not labeled when zoomed out.
  - `min_zoom_label` intentionally set to Z8, will not render before then
- [x] INPE name disappears when zooming in.
  - can't replicate, appearing all the way through Z19
- [x] FOUS s named twice when zoomed out but only once when zoomed in. #522
- [x] THRO the three section are hard to interpret.
  - ? requires further clarification...
- [x] MNRR the two sections are hard to interpret.
  - ? requires further clarification...
- [x] WICL marker not labeled NE of Texarkana.
  - ? requires further clarification...
  - label renders at Z9, which is intentional
  - unit boundary is not currently rendering, however. see #524
- [x] LECL is missing.
  - we do not currently render/support National Trails
- [x] ULSG name not showing when zoomed out (in St. Louis).  There are two NHS in name when zoomed way in.
  - `min_zoom_label` intentionally set to Z9, will not render before then
  - label rendering twice is a problem, see #525
- [x] JEFF name only shows when zoomed way in. #526
- [x] EFMO is named twice when zoomed out but only once when zoomed in. #527
- [x] BRVB name is not showing when zoomed out.
  - `min_zoom_label` intentionally set to Z7, will not render before then
- [ ] ABLI with the site covering a lot of area, the label is between the two units and they are hard to find. #528  
- [x] ANJO separated small units, hard to find.  
  - it's here http://insidemaps.nps.gov/park-tiles-3/#17/36.15849/-82.83423, via the search bar
  - requires further clarification...
- [x] CAHA missing boundary Rodanthe to Oregon Inlet.
  - this is the park preference #513  
- [x] CALO sound side boundary is not correct.  
  - this is pulling from the latest available Lands dataset #465
- [x] CARI missing second plantation.  
  - this is pulling from the latest available Lands dataset #467 
- [x] CASA missing expansion west.  
  - this is pulling from the latest available Lands dataset #469 
- [x] CHAT no legislative boundary, missing ownership.  
  - this is pulling from the latest available Lands dataset #470  
- [x] CHCH Moccasin Bend missing. Small pieces get lost expansion to west of lLookout Mountain missing.  
  - this is pulling from the latest available Lands dataset #471 
- [x] CONG missing legislated boundary.  
  - this is pulling from the latest available Lands dataset #473
- [x] FOCA boundary not correct.  
  - this is pulling from the latest available Lands dataset #480  
- [x] FODO missing Ft Heiman unit in KY.  Missing expansion.  
  - this is pulling from the latest available Lands dataset #447
- [x] FOFR Bloody Marsh missing.  
  - this is pulling from the latest available Lands dataset #481  
- [x] FORA has no legislative boundary, missing ownership.  
  - this is pulling from the latest available Lands dataset #484  
- [x] FOSU Ft Moultrie boundary missing, Fort Sumpter missing, tour boat terminal not identified, again small pieces get lost.  
  - this is pulling from the latest available Lands dataset #485  
- [x] GUCO missing westward expansion, N boundary may have a question.  
  - this is pulling from the latest available Lands dataset #486  
- [x] JAZZ missing.  
  - it's here http://insidemaps.nps.gov/park-tiles-3/#19/29.96311/-90.06740
  - this is missing from the Lands dataset, so this boundary is directly from SERO
- [ ] JELA units in outlying towns not labeled as JELA unless you know where they are you won't find them. #529  
- [x] LIRI missing new boundary.  
  - this is pulling from the latest available Lands dataset #491  
- [ ] NATC again small pieces get lost. #530  
- [x] NATR southern terminus needs revision.
  - this is pulling from the latest available Lands dataset #497  
- [x] NISI missing added tract west of park.  
  - this is pulling from the latest available Lands dataset #498
- [x] OBED missing boundary. 
  - we have a boundary on file, but for reason it is not currently rendering. see #531  
- [x] SEMO missing. 
- just added via #411  
- [x] SHIL main unit MIIS legislation boundary, missing Corinth and Davis Bridge.
  - this is pulling from the latest available Lands dataset #504  
- [x] TIMU boundary not right.  
  - this is pulling from the latest available Lands dataset #506  
- [x] VICK boundary at Waltersville needs revision  Pemberton House missing 3 new units missing. Grants Canal in LA missing again small pieces get lost.
  - this is pulling from the latest available Lands dataset #509
  - adding custom labels under consideration via #533
- [x] CATO this isn't the legislated boundar.  Fee-Other parcels are included in boundary.
  - this will be addressed via #347 - the current boundary came directly from the park
- [x] The following units need their boundaries updated (CAWO, CLBA COGA, FOTH, FOWA, FRDE, FRDO, JEME, KWVM, LIME. LYBA, MABE, MLNM, PAAV, VVWM)
  - all of these will be addressed via #347 - we are working directly with NCR
- [x] The following boundaries are missing significant details (EVER, BISC, BICY)
  - these are all pulling from the latest available Lands dataset #479, #462, #461

**Comment by chadlawlis** [comment]
Boundaries we need from Lands:
- ALEU
- COLT
- INUP
- MAPR
- NEPE
- OKCI
- WACO

**Comment by chadlawlis** [comment]
All unresolved issues have been separated into their own issues, which are listed alongside the description. Closing.
