### ISSUE TITLE
Add missing geometries for park labels

### ISSUE THREAD

**Issue by mtaylorlong** [nationalparkservice/places-data#726]
I noticed that there are a handful of records in the `park_labels` table that don't have geometries. Some are National Trials, which have their own complications, but some are just regular parks, which should be easy to fix.

**Labels missing geometries:**
- [ ] ~~Coltsville NP~~ (#182)
- [x] Yorktown Battlefield NHP (#547)
- [ ] ~~National Capital Parks~~ (#597)
- [ ] ~~Harriet Tubman Underground Railroad NM~~ (#178)
- [x] National Parks of New York Harbor (#725)
- [x] Aleutian World War II NHA (#234)
- [ ] ~~Capitol Hill Parks~~ (#579)
- [x] Historic Jamestown NHP (#547)
- [ ] ~~Blackstone River Valley NHC~~ (#414) 

We can check of the ones that are taken care of.

**Comment by chadlawlis** [comment]
I'll add comments here as I work through these...

COLT is intentionally not included on the map, for now, per guidance from Lands and Nigel @ NER (see #182). Once the unit is "official" Lands will share the boundary, at which point we'll add a label as well.

**Comment by chadlawlis** [comment]
YORK and JAME here: #547.

**Comment by chadlawlis** [comment]
National Capital Parks (NACA) isn't really a unit, so we can probably remove this from the database altogether. I kept the record in there for the time being - see #597 for more context.

**Comment by chadlawlis** [comment]
HATU falls into the same context as COLT, more context here https://github.com/nationalparkservice/places-data/issues/178#issuecomment-194425438

**Comment by chadlawlis** [comment]
I've been waiting on a point for ALEU from AKR for quite some time - open issue here #234. We could probably add a point ourselves and wait on AKR for the official geometry.

**Comment by chadlawlis** [comment]
Capitol Hill Parks (CAHE) isn't really a unit, or at least not a well defined one. Lands has a boundary for the unit, but it's just a buffer around a point. It was not included in the comprehensive NCR boundary update, though the record was maintained in a similar fashion to NACA. More context here #579.

**Comment by chadlawlis** [comment]
BLAC is a National Corridor, which we have not populated/maintained geometries for. Open issue here #414.

**Comment by chadlawlis** [comment]
**Conclusion**: at this point we can probably manually add label points for ALEU, JAME, and YORK. These all have open issues, so I'm all set here.

**Comment by chadlawlis** [comment]
ALEU, JAME, and YORK are taken care of so let's close this out.
